language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="therightfood.settings.travis"

services:
  - postgresql

branches:
  only:
    - stage

script:
  - ./manage.py test
