# Generated by Django 2.2.9 on 2020-02-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_auto_20200202_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='meal',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
